version: '3'
services:
  book01:
    image: lmsbooks:latest
    ports:
      - "7039-7046:8080"  # Dynamically allocate ports between 8087 and 8088
    environment:
      SPRING_PROFILES_ACTIVE: instance1,bootstrap,prod
    networks:
      - lms_network
    volumes:
      - "uploaded_files_volume_1:/tmp"
    deploy:
      replicas: 2
    privileged: true

  book02:
    image: lmsbooks:latest
    ports:
      - "7047-7057:8080"  # Dynamically allocate ports between 8089 and 8090
    environment:
      SPRING_PROFILES_ACTIVE: instance2,bootstrap,prod
    networks:
      - lms_network
    volumes:
      - "uploaded_files_volume_2:/tmp"
    deploy:
      replicas: 2
    privileged: true

networks:
  lms_network:
    external: true

volumes:
  uploaded_files_volume_1:
  uploaded_files_volume_2:
