services:
    lmsbooks_1:
        image: ghcr.io/ritapinto1230205/lmsbooks:latest
        container_name: books1_in_lms_network
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8087:8080"
        environment:
            SPRING_PROFILES_ACTIVE: instance1,bootstrap
        networks:
            - lms_network
        volumes:
            - "uploaded_files_volume_1:/tmp"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8087/health" ]
            interval: 30s
            timeout: 10s
            retries: 3

    lmsbooks_2:
        image: ghcr.io/ritapinto1230205/lmsbooks:latest
        container_name: books2_in_lms_network
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8088:8080"
        environment:
            SPRING_PROFILES_ACTIVE: instance2,bootstrap
        networks:
            - lms_network
        volumes:
            - "uploaded_files_volume_2:/tmp"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8088/health" ]
            interval: 30s
            timeout: 10s
            retries: 3

networks:
    lms_network:
        external: true

volumes:
    uploaded_files_volume_1:
    uploaded_files_volume_2:
