pipeline {
    agent any

    environment {
        MAVEN_HOME = '/opt/homebrew'
        DOCKER_HOST = 'unix:///var/run/docker.sock'
        DOCKER_BINARY = '/usr/local/bin/docker'
        SERVER_PORT = '2226'
        IMAGE_NAME = 'ghcr.io/ritapinto1230205/lmsbooks'
        IMAGE_TAG = 'latest'
        GITHUB_TOKEN_ID = 'GITHUB_TOKEN'
        DEPLOYMENT_APPROVED = false
    }

    stages {
          stage('Install Java 21.0.4-amzn with SDKMAN!') {
                        steps {
                            script {
                                sh '''
                                    # Instalar SDKMAN! (se necessário)
                                    if [ ! -d "$HOME/.sdkman" ]; then
                                      curl -s "https://get.sdkman.io" | bash
                                      source "$HOME/.sdkman/bin/sdkman-init.sh"
                                    fi
                                    # Instalar a versão do Java 21.0.4-amzn
                                    source "$HOME/.sdkman/bin/sdkman-init.sh"
                                    sdk install java 21.0.4-amzn || true  # Ignora se já estiver instalado
                                    sdk default java 21.0.4-amzn
                                '''
                            }
                        }
                    }

        stage('Check Out') {
            steps {
                echo 'Checking out the latest code...'
                checkout scm
            }
        }

        stage('Debug Environment') {
            steps {
                dir('lms-books') {
                    sh 'env'
                }
            }
        }

        stage('Check Docker') {
            steps {
                dir('lms-books') {
                    sh 'docker --version'
                }
            }
        }

        stage('Clean and Build Project') {
            steps {
                dir('lms-books') {
                    script {
                        sh """
                            ${MAVEN_HOME}/bin/mvn clean install
                        """
                    }
                }
            }
        }

       stage('Build Docker Image') {
            steps {
                dir('lms-books') {
                    script {
                        withCredentials([string(credentialsId: GITHUB_TOKEN_ID, variable: 'GITHUB_TOKEN')]) {
                            if (isUnix()) {
                                sh """
                                    echo \$GITHUB_TOKEN | docker login ghcr.io -u RitaPinto1230205 --password-stdin
                                    docker build -t ${IMAGE_NAME}:latest .
                                """
                            } else {
                                bat """
                                    echo %GITHUB_TOKEN% | docker login ghcr.io -u RitaPinto1230205 --password-stdin
                                    docker build -t ${IMAGE_NAME}:latest .
                                """
                            }
                        }
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                dir('lms-books') {
                    script {
                        withCredentials([string(credentialsId: GITHUB_TOKEN_ID, variable: 'GITHUB_TOKEN')]) {
                            if (isUnix()) {
                                sh """
                                    docker push ${IMAGE_NAME}:latest
                                """
                            } else {
                                bat """
                                    docker push ${IMAGE_NAME}:latest
                                """
                            }
                        }
                    }
                }
            }
        }

         stage('Wait for Manual Approval') {
                    steps {
                        input message: 'Deployment is ready. Do you want to continue?', parameters: [
                            booleanParam(defaultValue: false, description: 'Approve deployment?', name: 'DeployApproval')
                        ]
                        script {
                            DEPLOYMENT_APPROVED = params.DeployApproval
                        }
                    }
                }

        stage('Deploy with Docker Compose') {
                    steps {
                        script {
                            sh """

                                if ! docker ps --filter "name=rabbitmq_in_lms_network" --format '{{.Names}}' | grep -q rabbitmq_in_lms_network; then
                                  docker compose -f docker-compose-rabbitmq.yml up -d
                                else
                                  echo "RabbitMQ container already running."
                                fi

                                if ! docker ps --filter "name=postgres_in_lms_network" --format '{{.Names}}' | grep -q postgres_in_lms_network; then
                                  docker compose -f docker-compose-postgres.yml up -d
                                else
                                  echo "Postgres container already running."
                                fi


                                docker compose -f docker-compose.yml up -d --force-recreate

                            """
                        }
                    }
                }
            }

            post {
                success {
                    echo 'Pipeline completed successfully!'
                }
                failure {
                    echo 'Pipeline failed!'
                }
            }


        ////if containers are to be removed
        //     post {
        //         always {
        //             echo 'Cleaning up...'
        //             sh """
        //                 docker compose -f docker-compose.yml down || true
        //             """
        //         }
        //     }

        }
