pipeline {
    agent any

    environment {
        MAVEN_HOME = '/opt/homebrew'
        DOCKER_HOST = 'unix:///var/run/docker.sock'
        DOCKER_BINARY = '/usr/local/bin/docker'
        SERVER_PORT = '2226'
        IMAGE_NAME = 'ghcr.io/ritapinto1230205/lmsbooks'
        IMAGE_TAG = 'latest'
        GITHUB_TOKEN_ID = 'GITHUB_TOKEN'
        DEPLOYMENT_APPROVED = false
    }

    stages {
          stage('Install Java 21.0.4-amzn with SDKMAN!') {
                        steps {
                            script {
                                sh '''
                                    # Instalar SDKMAN! (se necessário)
                                    if [ ! -d "$HOME/.sdkman" ]; then
                                      curl -s "https://get.sdkman.io" | bash
                                      source "$HOME/.sdkman/bin/sdkman-init.sh"
                                    fi
                                    # Instalar a versão do Java 21.0.4-amzn
                                    source "$HOME/.sdkman/bin/sdkman-init.sh"
                                    sdk install java 21.0.4-amzn || true  # Ignora se já estiver instalado
                                    sdk default java 21.0.4-amzn
                                '''
                            }
                        }
                    }

        stage('Check Out') {
            steps {
                echo 'Checking out the latest code...'
                checkout scm
            }
        }

        stage('Debug Environment') {
            steps {
                dir('lms-books') {
                    sh 'env'
                }
            }
        }

        stage('Check Docker') {
            steps {
                dir('lms-books') {
                    sh 'docker --version'
                }
            }
        }

        stage('Clean and Build Project') {
            steps {
                dir('lms-books') {
                    script {
                        sh """
                            ${MAVEN_HOME}/bin/mvn clean install
                        """
                    }
                }
            }
        }

        stage('Run Tests Against Container') {
                    steps {
                        dir('lms-books') {
                            script {
                                sh """
                                    ${MAVEN_HOME}/bin/mvn verify -Dtest.container.url=http://localhost:${SERVER_PORT}
                                """
                            }
                        }
                    }
                }


        stage('Push Docker Image') {
            steps {
                dir('lms-books') {
                    script {
                        withCredentials([string(credentialsId: GITHUB_TOKEN_ID, variable: 'GITHUB_TOKEN')]) {
                            if (isUnix()) {
                                sh """
                                    docker push ${IMAGE_NAME}:latest
                                """
                            } else {
                                bat """
                                    docker push ${IMAGE_NAME}:latest
                                """
                            }
                        }
                    }
                }
            }
        }

       stage('Scale Up and Down Services') {
           steps {
               script {
                   // Pegue o número atual de instâncias
                   def currentScaleBook01 = 4 // Valor inicial (pode ser ajustado conforme o número de instâncias atuais)
                   def currentScaleBook02 = 4 // Valor inicial (pode ser ajustado conforme o número de instâncias atuais)

                   // Solicita ao usuário o número de instâncias desejadas
                   def scaling = input(
                       message: 'Escolha quantas instâncias de cada serviço você deseja adicionar ou remover:',
                       parameters: [
                           // Permitir aumentar ou diminuir as instâncias
                           number(defaultValue: currentScaleBook01, description: 'Número de instâncias do book01 (pode ser maior ou menor que o valor atual)', name: 'scaleBook01'),
                           number(defaultValue: currentScaleBook02, description: 'Número de instâncias do book02 (pode ser maior ou menor que o valor atual)', name: 'scaleBook02')
                       ]
                   )

                   // Mostra os valores definidos
                   echo "Deploying to Development Environment with scaling: book01=${scaling.scaleBook01}, book02=${scaling.scaleBook02}"

                   // Definindo tempo limite para a operação de scaling
                   def scaleTimeout = 60

                   dir('lms-books') {
                       // Executando o scale down e up
                       sh """
                           gtimeout ${scaleTimeout} docker-compose -f docker-compose-test.yml down --remove-orphans
                           gtimeout ${scaleTimeout} docker-compose -f docker-compose-test.yml up --scale book01=${scaling.scaleBook01} --scale book02=${scaling.scaleBook02} -d
                       """
                   }
               }
           }
       }



         stage('Wait for Manual Approval') {
                    steps {
                        input message: 'Deployment is ready. Do you want to continue?', parameters: [
                            booleanParam(defaultValue: false, description: 'Approve deployment?', name: 'DeployApproval')
                        ]
                        script {
                            DEPLOYMENT_APPROVED = params.DeployApproval
                        }
                    }
                }

        stage('Deploy Using Docker Compose') {
            steps {
                dir('lms-books') {
                    script {
                        if (isUnix()) {
                            sh '''
                                docker-compose down
                                docker-compose pull
                                docker-compose up -d
                            '''
                        } else {
                            bat '''
                                docker-compose down
                                docker-compose pull
                                docker-compose up -d
                            '''
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
         always {
                    echo 'Cleaning up resources...'
                    dir('lms-books') {
                        sh 'docker-compose down --remove-orphans || true'
                    }
                }
    }
}
